/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:c2522a90-1409-4ddc-b542-6f0e6d8096f0",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_VairqcrRe",
    "aws_user_pools_web_client_id": "518b2kqdmu8gqaja55vfq6b0ma",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://x66etg6iovhdpmsp77ofwsn7mu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "personalstoragevault52315f8d64cf45d2a1c86a9668a34847-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
